name: flutter_lisheng_entertainment
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  video_player: ^0.10.8+1
  chewie: ^0.9.8+1
  #flutter_screenutil: ^0.6.1
  #轮播Banner
  #flutter_banner_swiper: ^0.1.4
  flutter_swiper: ^1.1.6
  flutter_picker: ^1.1.0
  #轮播组件
  carousel_pro: ^1.0.0
  #刷新控件（上拉 下拉刷新）
  pull_to_refresh: ^1.5.7
  retrofit: any
  logger: any  #for logging purpose
  #分享
  share: ^0.6.3+3
  #flutter packages pub run build_runner build //使用 build_runner 生成 .g.dart 文件
    #
    #flutter packages pub run build_runner wacth //监控生成文件，如果有改动时自动生成/更新 .g.dart 文件
    #
    #就ok了
    #
    #还没有生成.g.dart文件或者报错的运行下面的命令
    #
    #cd 你的工程目录
    #
    #flutter packages pub run build_runner build --delete-conflicting-outputs  //删除并重新创建.g.dart文件
    #
    #没有生成的再运行一下
    #
    #flutter packages pub run build_runner build
    #————————————————
  #版权声明：本文为CSDN博主「辰辰远」的原创文章，遵循 CC 4.0 BY-SA 版权协议，转载请附上原文出处链接及本声明。
  #原文链接：https://blog.csdn.net/worship_Kill/article/details/102892349
  #flutter packages pub run build_runner build 自动生成 Author.g.dart
  json_annotation: any
  dio: ^3.0.8
  shared_preferences: ^0.5.6+3
  fluttertoast: ^3.1.3
  #工具类
  flustars: ^0.2.6+1
  #获取设备信息
  package_info: ^0.4.0+12
  sqflite: ^1.2.2
  popup_windows: ^0.0.1
  event_bus: ^1.1.0
  cached_network_image: ^2.0.0
  image_picker: ^0.6.3+1
  image_cropper: ^1.2.1
  webview_flutter: ^0.3.19+7

dev_dependencies:
  retrofit_generator: any
  build_runner: any
  json_serializable: any
  flutter_native_splash: ^0.1.9
  flutter_test:
    sdk: flutter

flutter_native_splash:
  image: resource/imgs/icon_splash.png
  color: "42a5f5"
  fill: true
  android: false

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
#    - images/a_dot_burr.jpeg
#    - images/a_dot_ham.jpeg
    - resource/login_video.mp4
    - resource/imgs/icon_account.png
    - resource/imgs/icon_custom.png
    - resource/imgs/icon_login_change_group.png
    - resource/imgs/icon_password.png
    - resource/imgs/icon_login_logo.png
    - resource/imgs/icon_home_top_bg.png
    - resource/imgs/icon_home_custom.png
    - resource/imgs/icon_setting.png
    - resource/imgs/icon_head.png
    - resource/imgs/icon_recharge.png
    - resource/imgs/icon_withdraw_money.png
    - resource/imgs/icon_transfer_accounts.png
    - resource/imgs/icon_agent.png
    - resource/imgs/icon_usercenter.png
    - resource/imgs/icon_msg.png
    - resource/imgs/icon_activity.png
    - resource/imgs/icon_lottery_center.png
    - resource/imgs/icon_game.png
    - resource/imgs/banner.png
    - resource/imgs/icon_splash.png
    - resource/imgs/icon_back.png
    - resource/imgs/icon_right_arrow.png
    - resource/imgs/icon_set_update_version.png
    - resource/imgs/icon_set_help.png
    - resource/imgs/icon_set_share.png
    - resource/imgs/icon_set_about.png
    - resource/imgs/icon_set_switch.png
    - resource/imgs/icon_set_fingerprint.png
    - resource/imgs/icon_withdrawal_money.png
    - resource/imgs/icon_lottery_report.png
    - resource/imgs/icon_modify_pass.png
    - resource/imgs/icon_betting_record.png
    - resource/imgs/icon_bank.png
    - resource/imgs/icon_account_change_record.png
    - resource/imgs/icon_cash_password.png
    - resource/imgs/icon_team_report.png
    - resource/imgs/icon_team_bet.png
    - resource/imgs/icon_team_account_change.png
    - resource/imgs/icon_team_overview.png
    - resource/imgs/icon_recharge_record.png
    - resource/imgs/icon_agency_bonus.png
    - resource/imgs/icon_withdrawal_record.png
    - resource/imgs/icon_agent_vip.png
    - resource/imgs/icon_agent_open_account.png
    - resource/imgs/icon_modify_password.png
    - resource/imgs/icon_msg_banner.png
    - resource/imgs/icon_choice_up.png
    - resource/imgs/icon_lottery_center_banner.png
    - resource/imgs/icon_cp_cq_ssc.png
    - resource/imgs/icon_return_point.png
    - resource/imgs/icon_open_accout.png
    - resource/imgs/icon_radio_bg_selection.png
    - resource/imgs/icon_radio_bg.png
    - resource/imgs/icon_right_allow_white.png
    - resource/imgs/icon_close_dialog.png
    - resource/imgs/icon_game_title.png
    - resource/imgs/icon_betting_cp_question.png
    - resource/imgs/icon_trend_set_choice.png
    - resource/imgs/icon_delete_alone_shopping_cart.png
    - resource/imgs/icon_gd_11_choice_5.png
    - resource/imgs/icon_often_playcolor_variety.png
    - resource/imgs/icon_choice_add_cp_type.png
    - resource/imgs/icon_home_bg.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
